apiVersion: v1
kind: ReplicationController
metadata:
  name: kubestats-app
spec:
  replicas: 3 
  selector:
    name: kubestats
    version: v4
  template:
    metadata:
      labels:
        name: kubestats
        version: v4
    spec:
      containers:
      - name: kubestats
        image: gcr.io/kubernetes-playground-176304/kubestats:latest
        ports:
        - containerPort: 5000
